# Build & deploy pkgdown site to gh-pages
on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Evita builds simultáneos del sitio
    concurrency:
      group: pkgdown-${{ github.event_name == 'pull_request' && github.head_ref || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        shell: Rscript {0}
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)

      - name: Deploy to gh-pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: docs
          clean: false